[package]
name = "volto"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
=======
serde_json = "1.0"
quick_xml = "0.4"
>>>>>>> master
=======
serde_json = "1.0"
quick_xml = "0.4"
>>>>>>> master
