[package]
name = "volto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
quick-xml = "0.27"
thiserror = "1.0"
calamine = "0.20"
pyo3 = { version = "0.20", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
